routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




// Route::get('/guru/create', 'TeacherController@create');
// Route::post('/guru', 'TeacherController@store');
// Route::get('/guru', 'TeacherController@index');
// Route::get('/guru/{id}', 'TeacherController@show');
// Route::get('/guru/{id}/edit', 'TeacherController@edit');
// Route::put('/guru/{id}', 'TeacherController@update');
// Route::delete('/guru/{id}', 'TeacherController@destroy');
// Route::get('/guru/point/edit/{id}', 'TeacherController@editpoint');
Route::get('/guru/cetak', 'TeacherController@cetak')->name('guru.cetak');
// route guru 
Route::resource('guru', 'TeacherController');

// Route::get('/jadwal/create', 'JadwalController@create');
// Route::post('/jadwal', 'JadwalController@store');
// Route::get('/jadwal', 'JadwalController@index');
// // Route::get('/jadwal/{id}', 'JadwalController@show');
// Route::get('/jadwal/{id}/edit', 'JadwalController@edit');
// Route::put('/jadwal/{id}', 'JadwalController@update');
// Route::delete('/jadwal/{id}', 'JadwalController@destroy');

Route::resource('jadwal', 'JadwalController');
Route::get('/jadwal/cetak', 'JadwalController@cetak')->name('jadwal.cetak');


Route::resource('siswa', 'SiswaController');

Route::get('/jadwal/show/cetak', 'JadwalController@cetakpoint');

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');


// route utama
Route::get('/dashboard', 'HomeController@index')->name('dashboard');
Route::get('/', 'HomeController@index')->middleware('auth');

app/Siswa.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Siswa extends Model
{
    protected $table = 'siswa';
    protected $guarded = [];
    protected $primaryKey = 'id';

    public function user()
    {
        return $this->belongsTo('App\User', 'user_id');
    }
}

app/Http/Controllers/SiswaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Siswa;
use Auth;

class SiswaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $siswa = Siswa::all();
        return view('siswa.index', compact('siswa'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('siswa.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nisn' => 'required|unique:siswa',
            'nama_lengkap' => 'required',
            'tempat_lahir' => 'required',
            'tanggal_lahir' => 'required',
            'agama' => 'required',
            'alamat' => 'required',
            'jenis_kelamin' => 'required',
            'rombel' => 'required',
            'telepon' => 'required|unique:siswa',
        ]);

        $siswa = Siswa::create([
            "nisn" => $request["nisn"],
            "nama_lengkap" => $request["nama_lengkap"],
            "tempat_lahir" => $request["tempat_lahir"],
            "tanggal_lahir" => $request["tanggal_lahir"],
            "agama" => $request["agama"],
            "alamat" => $request["alamat"],
            "jenis_kelamin" => $request["jenis_kelamin"],
            "rombel" => $request["rombel"],
            "telepon" => $request["telepon"],
            "user_id" => Auth::id()
        ]);
        //Alert::success('Sukses', 'Data berhasil disimpan!');

        return redirect('/siswa')->with('success', 'Data berhasil disimpan!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $siswa = Siswa::find($id);
        // dd($guru);
        return view('siswa.show', compact('siswa'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $siswa = Siswa::find($id);
        // dd($guru);

        return view('siswa.edit', compact('siswa'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'nisn' => 'required',
            'nama_lengkap' => 'required',
            'tempat_lahir' => 'required',
            'tanggal_lahir' => 'required',
            'agama' => 'required',
            'alamat' => 'required',
            'jenis_kelamin' => 'required',
            'rombel' => 'required',
            'telepon' => 'required',
        ]);
        $update = Siswa::where('id', $id)->update([
            "nisn" => $request["nisn"],
            "nama_lengkap" => $request["nama_lengkap"],
            "tempat_lahir" => $request["tempat_lahir"],
            "tanggal_lahir" => $request["tanggal_lahir"],
            "agama" => $request["agama"],
            "alamat" => $request["alamat"],
            "jenis_kelamin" => $request["jenis_kelamin"],
            "rombel" => $request["rombel"],
            "telepon" => $request["telepon"]
        ]);

        return redirect('/siswa')->with('success', 'Identitas berhasil di update!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Siswa::destroy($id);
        return redirect('/siswa')->with('success', 'Identitas berhasil di hapus!');
    }
}

resources/views/siswa/cetakdatasiswa.blade.php
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="sparkline13-list">
        <div class="sparkline13-hd">
            <center>

                <div class="main-sparkline13-hd">
                    <h1>Tabel <span class="table-project-n">Daftar</span>Siswa</h1>
                </div>
            </center>
        </div>
        <div class="card">
            <div class="card-header">
                <h3 class="card-title"></h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
                <!-- <a class="btn btn-primary mb-5" href="/guru/create">Buat Daftar Guru</a> -->
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th style="width: 10px">No</th>
                            <th>NIP</th>
                            <th>Nama Lengkap</th>
                            <th>Tempat lahir</th>
                            <th>Tanggal lahir</th>
                            <th>Agama</th>
                            <th>Alamat</th>
                            <th>Jenis Kelamin</th>
                            <th>Pengampu</th>
                            <th>Telepon</th>
                            <!-- <th>Aksi</th> -->
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($siswa as $key => $siswa)
                        <tr>
                            <td>{{ $key+1 }}</td>
                            <td>{{ $siswa->nisn }}</td>
                            <td>{{ $siswa->nama_lengkap }}</td>
                            <td>{{ $siswa->tempat_lahir }}</td>
                            <td>{{ $siswa->tanggal_lahir }}</td>
                            <td>{{ $siswa->agama }}</td>
                            <td>{{ $siswa->alamat }}</td>
                            <td>{{ $siswa->jenis_kelamin }}</td>
                            <td>{{ $siswa->rombel }}</td>
                            <td>{{ $siswa->telepon }}</td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

resources/views/siswa/create.blade.php
@extends('adminlte.master')

@section('content')
<div class="col-md-auto mt-2">
    <!-- general form elements disabled -->
    <div class="card card-warning">
        <div class="card-header">
            <h3 class="card-title">Tambah Data Siswa</h3>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
            <form action="/siswa" role="form" method="POST">
                @csrf
                <!-- <div class="row"> -->
                <div class="form-group">
                    <label class="col-form-label" for="inputSuccess"></i>NISN</label>
                    <input name="nisn" for="nisn" id="nisn" type="text" class="form-control" value="{{old('nisn','')}}" placeholder="NISN">
                    @error('nisn')
                    <div class="alert alert-danger">{{$message}}</div>
                    @enderror
                </div>



                <div class="form-group">
                    <label class="col-form-label" for="inputSuccess"></i>NAMA LENGKAP</label>
                    <input name="nama_lengkap" for="nama_lengkap" id="nama_lengkap" type="text" class="form-control" value="{{old('nama_lengkap','')}}" placeholder="Nama lengkap">
                    @error('nama_lengkap')
                    <div class="alert alert-danger">{{$message}}</div>
                    @enderror
                </div>


                <div class="form-group">
                    <label class="col-form-label" for="inputSuccess"></i>TEMPAT LAHIR</label>
                    <input name="tempat_lahir" for="tempat_lahir" id="tempat_lahir" type="text" class="form-control" value="{{old('tempat_lahir','')}}" placeholder="Tempat lahir">
                    @error('tempat_lahir')
                    <div class="alert alert-danger">{{$message}}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label class="col-form-label" for="inputSuccess"></i>TANGGAL LAHIR</label>
                    <input name="tanggal_lahir" for="tanggal_lahir" id="tanggal_lahir" type="date" class="form-control" value="{{old('tanggal_lahir','')}}" placeholder="Tanggal lahir">
                    @error('tanggal_lahir')
                    <div class="alert alert-danger">{{$message}}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label class="col-form-label" for="inputSuccess"></i>AGAMA</label>
                    <input name="agama" for="agama" id="agama" type="text" class="form-control" value="{{old('agama','')}}" placeholder="Agama">
                    @error('agama')
                    <div class="alert alert-danger">{{$message}}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label class="col-form-label" for="inputSuccess"></i>ALAMAT</label>
                    <textarea name="alamat" for="alamat" id="alamat" type="text" class="form-control" value="{{old('alamat','')}}" placeholder="Alamat">{{old('alamat','')}}</textarea>
                    @error('alamat')
                    <div class="alert alert-danger">{{$message}}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label class="col-form-label" for="inputSuccess"></i>JENIS KELAMIN</label>
                    <select name="jenis_kelamin" for="jenis_kelamin" id="jenis_kelamin" value="{{old('jenis_kelamin','')}}" class="form-control">
                        <option value="none" selected="" disabled="">Jenis kelamin</option>
                        <option value="Laki-Laki">Laki-laki</option>
                        <option value="Perempuan">Perempuan</option>
                    </select>
                    @error('jenis_kelamin')
                    <div class="alert alert-danger">{{$message}}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label class="col-form-label" for="inputSuccess">ROMBEL</i></label>
                    <input name="rombel" for="rombel" id="rombel" type="text" class="form-control" value="{{old('rombel','')}}" placeholder="rombel">
                    @error('rombel')
                    <div class="alert alert-danger">{{$message}}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label class="col-form-label" for="inputSuccess">TELEPON</i></label>
                    <input name="telepon" for="telepon" id="telepon" type="number" class="form-control" value="{{old('telepon','')}}" placeholder="No telepon">
                    @error('telepon')
                    <div class="alert alert-danger">{{$message}}</div>
                    @enderror
                </div>



                <!-- </div> -->
                <div class="row">
                    <div class="col-lg-12">
                        <div class="payment-adress">
                            <button type="submit" class="btn btn-primary waves-effect waves-light">Buat</button>
                            <a href="/siswa" class="btn btn-primary">Kembali</a>
                        </div>
                    </div>
                </div>

                <!-- input states -->
            </form>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->
</div>

@endsection

resources/views/siswa/edit.blade.php
@extends('adminlte.master')

@section('content')
<div class="col-md-auto mt-2">
    <!-- general form elements disabled -->
    <div class="card card-warning">
        <div class="card-header">
            <h3 class="card-title">Edit Data Siswa {{$siswa->nama_lengkap}}</h3>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
            <form action="/siswa/{{$siswa->id}}" role="form" method="POST">
                @csrf
                @method('PUT')
                <!-- <div class="row"> -->
                <div class="form-group">
                    <label class="col-form-label" for="inputSuccess"></i>NISN</label>
                    <input name="nisn" for="nisn" id="nisn" type="text" class="form-control" value="{{old('nisn',$siswa->nisn)}}" placeholder="NIP">
                    @error('nip')
                    <div class="alert alert-danger">{{$message}}</div>
                    @enderror
                </div>

                <div class="form-group">
                    <label class="col-form-label" for="inputSuccess"></i>NAMA LENGKAP</label>
                    <input name="nama_lengkap" for="nama_lengkap" id="nama_lengkap" type="text" class="form-control" value="{{old('nama_lengkap',$siswa->nama_lengkap)}}" placeholder="Nama lengkap">
                    @error('nama_lengkap')
                    <div class="alert alert-danger">{{$message}}</div>
                    @enderror
                </div>

                <div class="form-group">
                    <label class="col-form-label" for="inputSuccess"></i>TEMPAT LAHIR</label>
                    <input name="tempat_lahir" for="tempat_lahir" id="tempat_lahir" type="text" class="form-control" value="{{old('tempat_lahir',$siswa->tempat_lahir)}}" placeholder="Tempat lahir">
                    @error('tempat_lahir')
                    <div class="alert alert-danger">{{$message}}</div>
                    @enderror
                </div>

                <div class="form-group">
                    <label class="col-form-label" for="inputSuccess"></i>TANGGAL LAHIR</label>
                    <input name="tanggal_lahir" for="tanggal_lahir" id="tanggal_lahir" type="date" class="form-control" value="{{old('tanggal_lahir',$siswa->tanggal_lahir)}}" placeholder="Tanggal lahir">
                    @error('tanggal_lahir')
                    <div class="alert alert-danger">{{$message}}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label class="col-form-label" for="inputSuccess"></i>AGAMA</label>
                    <input name="agama" for="agama" id="agama" type="text" class="form-control" value="{{old('agama',$siswa->agama)}}" placeholder="Agama">
                    @error('agama')
                    <div class="alert alert-danger">{{$message}}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label class="col-form-label" for="inputSuccess"></i>ALAMAT</label>
                    <textarea name="alamat" for="alamat" id="alamat" type="text" class="form-control" value="{{old('alamat',$siswa->alamat)}}" placeholder="Alamat">{{old('alamat',$siswa->alamat)}}</textarea>
                    @error('alamat')
                    <div class="alert alert-danger">{{$message}}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label class="col-form-label" for="inputSuccess"></i>JENIS KELAMIN</label>
                    <select name="jenis_kelamin" for="jenis_kelamin" id="jenis_kelamin" value="{{old('jenis_kelamin',$siswa->jenis_kelamin)}}" class="form-control">
                        <option value="none" selected="" disabled="">Jenis kelamin</option>
                        <option value="Laki-Laki">Laki-laki</option>
                        <option value="Perempuan">Perempuan</option>
                    </select>
                    @error('jenis_kelamin')
                    <div class="alert alert-danger">{{$message}}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label class="col-form-label" for="inputSuccess">ROMBEL</i></label>
                    <input name="rombel" for="rombel" id="rombel" type="text" class="form-control" value="{{old('rombel',$siswa->rombel)}}" placeholder="pengampu">
                    @error('pengampu')
                    <div class="alert alert-danger">{{$message}}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label class="col-form-label" for="inputSuccess">TELEPON</i></label>
                    <input name="telepon" for="telepon" id="telepon" type="number" class="form-control" value="{{old('telepon',$siswa->telepon)}}" placeholder="No telepon">
                    @error('telepon')
                    <div class="alert alert-danger">{{$message}}</div>
                    @enderror
                </div>



                <!-- </div> -->
                <div class="row">
                    <div class="col-lg-12">
                        <div class="payment-adress">
                            <button type="submit" class="btn btn-primary waves-effect waves-light">Edit</button>
                            <a href="/siswa" class="btn btn-primary">Kembali</a>
                        </div>
                    </div>
                </div>

                <!-- input states -->
            </form>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->
</div>

@endsection

resources/views/siswa/editpoint.blade.php
@extends ('adminlte.master')

@section('content')
<div class="position-absolute">
    <h2>Edit Data Guru</h2>


    <div class="input-group align-middle">

        <select name="editpoint" id="editpoint" class="form-select" id="inputGroupSelect04">
            <option holder value="">Pilih Data Yang Akan Diedit</option>
            @forelse ($select as $s)
            <option value="{{ $s->id }}" {{ old('editpoint', $s->id) == $s->id ? 'selected' : '' }}> {{ $s->nama_lengkap }}</option>
            @empty
            <p>No Data</p>
            @endforelse
        </select>
        <a href="{{route('guru.edit',['guru' => $s->id])}}" class="btn btn-primary">Edit</a>

    </div>

</div>

@endsection

resources/views/siswa/index.blade.php
@extends('adminlte.master')

@section('content')

<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
  <div class="sparkline13-list">
    <div class="sparkline13-hd">
      <div class="main-sparkline13-hd">
        <h1>Tabel <span class="table-project-n">Daftar</span> Siswa</h1>
      </div>
    </div>
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"></h3>
      </div>
      <!-- /.card-header -->
      <div class="card-body">
        @if(session('success'))
        <div class="alert alert-success">
          {{ session('success') }}
        </div>
        @endif

        <a class="btn btn-primary mb-3 btn-sm" href="/siswa/create"><i class="fas fa-plus-square"></a>
        <a class="btn btn-primary mb-3 btn-sm" href="/siswa/cetak"><i class="fas fa-print"></a>
        <table class="table table-bordered">
          <thead>
            <tr>
              <th style="width: 10px">No</th>
              <th>NISN</th>
              <th>Nama Lengkap</th>
              <th>Tempat lahir</th>
              <th>Tanggal lahir</th>
              <th>Agama</th>
              <th>Alamat</th>
              <th>Jenis Kelamin</th>
              <th>Rombel</th>
              <th>Telepon</th>
              <th>Aksi</th>
            </tr>
          </thead>
          <tbody>
            @forelse($siswa as $key => $siswa)
            <tr>
              <td>{{ $key+1 }}</td>
              <td>{{ $siswa->nisn }}</td>
              <td>{{ $siswa->nama_lengkap }}</td>
              <td>{{ $siswa->tempat_lahir }}</td>
              <td>{{ $siswa->tanggal_lahir }}</td>
              <td>{{ $siswa->agama  }}</td>
              <td>{{ $siswa->alamat }}</td>
              <td>{{ $siswa->jenis_kelamin }}</td>
              <td>{{ $siswa->rombel }}</td>
              <td>{{ $siswa->telepon }}</td>
              <td style="display: flex;">
                <a href="/siswa/{{ $siswa->id }}" class="btn btn-info btn-xs"><i class="fas fa-eye"></i></a>
                <a href="/siswa/{{ $siswa->id }}/edit" class="btn btn-default btn-xs"><i class="fas fa-edit"></i></a>
                <form action="/siswa/{{ $siswa->id }}" method="post">
                  @csrf
                  @method('DELETE')
                  <input type="submit" value="Hapus" class="btn btn-danger btn-xs">
                </form>
              </td>
            </tr>
            @empty
            <tr>
              <td colspan="11" align="center"> No Post</td>
            </tr>
            @endforelse
          </tbody>
        </table>
      </div>
      <!-- /.card-body -->
      <div class="card-footer clearfix">
        <ul class="pagination pagination-sm m-0 float-right">
          <li class="page-item"><a class="page-link" href="#">«</a></li>
          <li class="page-item"><a class="page-link" href="#">1</a></li>
          <li class="page-item"><a class="page-link" href="#">2</a></li>
          <li class="page-item"><a class="page-link" href="#">3</a></li>
          <li class="page-item"><a class="page-link" href="#">»</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

@endsection

resources/views/siswa/show.blade.php
@extends('adminlte.master')

@section('content')

<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
    <div class="profile-info-inner">
        <div class="profile-img">
            <img src="{{asset('/adminlte/img/profile/1.jpg')}}" alt="">
        </div>
        <div class="profile-details-hr">
            <div class="row">
                <div class="col-lg-6 col-md-12 col-sm-12 col-xs-6">
                    <div class="address-hr">
                        <p><b>Nama Lengkap</b><br> {{$siswa->nama_lengkap}}</p>
                    </div>
                </div>
                <div class="col-lg-6 col-md-12 col-sm-12 col-xs-6">
                    <div class="address-hr tb-sm-res-d-n dps-tb-ntn">
                        <p><b>Tempat tanggal lahir</b><br> {{$siswa->tempat_lahir}}, {{$siswa->tanggal_lahir}}</p>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-6 col-md-12 col-sm-12 col-xs-6">
                    <div class="address-hr">
                        <p><b>Agama</b><br>{{$siswa->agama}} </p>
                    </div>
                </div>
                <div class="col-lg-6 col-md-12 col-sm-12 col-xs-6">
                    <div class="address-hr tb-sm-res-d-n dps-tb-ntn">
                        <p><b>Rombel</b><br> {{$siswa->rombel}}</p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6 col-md-12 col-sm-12 col-xs-6">
                    <div class="address-hr">
                        <p><b>Alamat</b><br>{{$siswa->alamat}} </p>
                    </div>
                </div>
                <div class="col-lg-6 col-md-12 col-sm-12 col-xs-6">
                    <div class="address-hr tb-sm-res-d-n dps-tb-ntn">
                        <p><b>Telepon</b><br> {{$siswa->telepon}}</p>
                    </div>
                </div>
            </div>
            <div>
                <a href="/siswa" class="btn btn-primary">Kembali</a>
            </div>
            <!-- <div class="row">
                                    <div class="col-lg-12">
                                        <div class="address-hr">
                                            <p><b>Address</b><br> E104, catn-2, Chandlodia Ahmedabad Gujarat, UK.</p>
                                        </div>
                                    </div>
                                </div> -->
            <!-- <div class="row">
                                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                                        <div class="address-hr">
                                            <a href="#"><i class="fa fa-facebook"></i></a>
                                            <h3>500</h3>
                                        </div>
                                    </div>
                                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                                        <div class="address-hr">
                                            <a href="#"><i class="fa fa-twitter"></i></a>
                                            <h3>900</h3>
                                        </div>
                                    </div>
                                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                                        <div class="address-hr">
                                            <a href="#"><i class="fa fa-google-plus"></i></a>
                                            <h3>600</h3>
                                        </div>
                                    </div>
                                </div> -->
        </div>
    </div>
</div>

@endsection